name: Lint & Vercel Build Test

on: [push, pull_request]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --fix || true

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel settings
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Simulate Vercel Build
        run: vercel build
